author = "stsenhor"
baseURL = "https://stsenhor.github.io/"
languageCode = "ja"
theme = "hugo-flex"
title = "TBOU"

[params]
color = "black"

[menu]
[[menu.nav]]
name = "About"
url = "about/"
weight = "1"
[[menu.nav]]
name = "Posts"
url = "post/"
weight = "2"